version: 0.0
os: windows
files:
  - source: \Windchill\codebase
    destination: C:\ptc\Windchill\codebase
  - source: \Windchill\src
    destination: C:\ptc\Windchill\src
hooks:
  AfterInstall:
    - location: scripts\restart_server.bat
      timeout: 900
